version: '3'
services:
  db:
    image: mysql:5.7.33
    platform: linux/amd64
    volumes:
      - test_devise_two_factor_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      OTP_SECRET_ENCRYPTION_KEY: 01234567890abcdef01234567890abcdef
volumes:
  test_devise_two_factor_db:
